name: submark
version: '0.4.0'
synopsis: Extract a part from CommonMark/Markdown docs
category: Text
author: Hong Minhee
maintainer: hong.minhee@gmail.com
copyright: "\xa9 2017\u20132022 Hong Minhee"
license: GPL-3
github: dahlia/submark
stability: alpha
extra-source-files:
- README.md
- CHANGELOG.md
dependencies:
- base >= 4.7 && < 5
- cmark >= 0.5.6 && < 0.7.0
- text < 3
flags:
  static:
    description: Static link
    manual: true
    default: false
library:
  source-dirs: src
  dependencies:
  - regex-tdfa >= 1.3.1.2 && < 1.4
  ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
executables:
  submark:
    main: Main.hs
    source-dirs: app
    dependencies:
    - submark
    - optparse-applicative >= 0.13.2.0 && < 0.19.0.0
    when:
    - condition: flag(static)
      then:
        ghc-options:
        - -Wall
        - -fwarn-incomplete-uni-patterns
        # Static link
        - -static
        - -optl-static
        - -optl-pthread
        - -optc-Os
        - -fPIC
      else:
        ghc-options:
        - -Wall
        - -Wincomplete-uni-patterns
    ghc-options:
    - -Wall
    - -Wincomplete-uni-patterns
tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
    - hspec >= 2.4.4 && < 3.0.0
    - submark
    - template-haskell >= 2.5
    ghc-options:
    - -Wno-x-partial
  hlint:
    main: Main.hs
    source-dirs: lint
    dependencies:
    - hlint >= 2.0.9 && < 4
