name: build
on:
  push:
  schedule:
  - cron: '59 14 * * *'
  pull_request:

jobs:
  test:
    permissions:
      contents: read
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
        - os: ubuntu-24.04-arm
        - os: macos-15-intel
          artifact_name: macOS-x86_64-executable
        - os: macos-15
          artifact_name: macOS-aarch64-executable
        - os: windows-2025
          artifact_name: Windows-win64-executable
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - uses: haskell-actions/setup@v2
      with:
        enable-stack: true
    - name: Cache Stack files (non-Windows)
      if: "runner.os != 'Windows'"
      uses: actions/cache@v5
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          ~/.stack
        key: stack-${{ runner.os }}-${{ runner.arch }}
    - name: Cache Stack files (Windows)
      if: "runner.os == 'Windows'"
      uses: actions/cache@v5
      with:
        path: |
          %APPDATA%\cabal\packages
          %APPDATA%\cabal\store
          %APPDATA%\stack
        key: stack-${{ runner.os }}-${{ runner.arch }}
    - name: Resolve dependencies
      run: stack install --test --only-dependencies
    - name: Build
      run: stack build --test
    - name: Test
      run: stack test
    - name: Build for release (Windows)
      if: runner.os == 'Windows'
      run: stack build --flag submark:static --copy-bins
    - name: Build for release (macOS)
      if: runner.os == 'macOS'
      run: stack build --copy-bins
    - id: bin-path
      if: runner.os != 'Linux'
      shell: bash
      run: |
        echo "bin-path=$(stack path --local-bin)/submark" >> "$GITHUB_OUTPUT"
    - uses: crazy-max/ghaction-upx@v4
      if: runner.os == 'Windows'
      with:
        files: ${{ steps.bin-path.outputs.bin-path }}.exe
        args: "-9"
    - if: runner.os != 'Linux'
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ steps.bin-path.outputs.bin-path }}*
        if-no-files-found: error
    - if: runner.os != 'Windows'
      run: 'grep "Version $(stack query locals submark version)" CHANGELOG.md'
    - if: github.ref_type == 'tag' && runner.os != 'Windows'
      run: '[[ "$(stack query locals submark version)" = "$GITHUB_REF_NAME" ]]'

  check:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: read
    env:
      CHECKMATE_DOWNLOAD_URL: https://github.com/dahlia/checkmate/releases/download/0.4.0/checkmate-linux-x86_64
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - run: |
        set -evx
        mkdir -p ~/bin
        curl -L -o ~/bin/checkmate "$CHECKMATE_DOWNLOAD_URL"
        chmod +x ~/bin/checkmate
        ~/bin/checkmate github \
          --token "${{ secrets.GITHUB_TOKEN }}" \
          --login "$GITHUB_REPOSITORY_OWNER" \
          --repo "${GITHUB_REPOSITORY#*/}" \
          --pr "$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"

  docker-image:
    permissions:
      contents: read
      packages: write
    env:
      IMG_REPO: ghcr.io/${{ github.repository }}
      IMG_TAG: git-${{ github.sha }}
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
          platform: linux/amd64
          image_arch: amd64
          artifact_name: Linux-x86_64-musl-executable
        - os: ubuntu-24.04-arm
          platform: linux/arm64
          image_arch: arm64
          artifact_name: Linux-aarch64-musl-executable
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - uses: docker/setup-buildx-action@v4
    - if: github.event_name != 'pull_request'
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        set -exv
        labels=(
          --label "org.opencontainers.image.url=https://github.com/$GITHUB_REPOSITORY"
        )
        if [[ "$GITHUB_REF_TYPE" = "tag" ]]; then
          labels+=(
            --label "org.opencontainers.image.version=$GITHUB_REF_NAME"
          )
        fi
        docker buildx build \
          --load \
          --platform "$PLATFORM" \
          --cache-from "type=gha,scope=submark-$IMAGE_ARCH" \
          --cache-to "type=gha,mode=max,scope=submark-$IMAGE_ARCH" \
          --tag "$IMG_REPO:$IMG_TAG-$IMAGE_ARCH" \
          "${labels[@]}" \
          .
      env:
        IMAGE_ARCH: ${{ matrix.image_arch }}
        PLATFORM: ${{ matrix.platform }}
    - if: github.event_name != 'pull_request'
      run: |
        set -exv
        docker push "$IMG_REPO:$IMG_TAG-$IMAGE_ARCH"
      env:
        IMAGE_ARCH: ${{ matrix.image_arch }}
    - run: |
        docker run "$IMG_REPO:$IMG_TAG-$IMAGE_ARCH" cat /usr/bin/submark \
          > "$RUNNER_TEMP/submark"
      env:
        IMAGE_ARCH: ${{ matrix.image_arch }}
    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ runner.temp }}/submark
        if-no-files-found: error

  docker-manifest:
    needs: docker-image
    permissions:
      contents: read
      packages: write
    env:
      IMG_REPO: ghcr.io/${{ github.repository }}
      IMG_TAG: git-${{ github.sha }}
    runs-on: ubuntu-24.04
    steps:
    - if: github.event_name == 'pull_request'
      run: echo "Skipping Docker manifest publishing for pull request."
    - if: github.event_name != 'pull_request'
      uses: docker/setup-buildx-action@v4
    - if: github.event_name != 'pull_request'
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - if: github.event_name != 'pull_request'
      run: |
        set -exv
        annotations=(
          --annotation "index:org.opencontainers.image.title=submark"
          --annotation "index:org.opencontainers.image.licenses=GPL-3"
          --annotation "index:org.opencontainers.image.description=Extract a part from CommonMark/Markdown docs"
          --annotation "index:org.opencontainers.image.url=https://github.com/$GITHUB_REPOSITORY"
        )
        if [[ "$GITHUB_REF_TYPE" = "tag" ]]; then
          annotations+=(
            --annotation "index:org.opencontainers.image.version=$GITHUB_REF_NAME"
          )
        fi
        docker buildx imagetools create \
          "${annotations[@]}" \
          --tag "$IMG_REPO:$IMG_TAG" \
          "$IMG_REPO:$IMG_TAG-amd64" \
          "$IMG_REPO:$IMG_TAG-arm64"
    - if: github.ref_type == 'tag'
      run: |
        set -exv
        annotations=(
          --annotation "index:org.opencontainers.image.title=submark"
          --annotation "index:org.opencontainers.image.licenses=GPL-3"
          --annotation "index:org.opencontainers.image.description=Extract a part from CommonMark/Markdown docs"
          --annotation "index:org.opencontainers.image.url=https://github.com/$GITHUB_REPOSITORY"
          --annotation "index:org.opencontainers.image.version=$GITHUB_REF_NAME"
        )
        docker buildx imagetools create \
          "${annotations[@]}" \
          --tag "$IMG_REPO:$GITHUB_REF_NAME" \
          "$IMG_REPO:$IMG_TAG-amd64" \
          "$IMG_REPO:$IMG_TAG-arm64"
        docker buildx imagetools create \
          "${annotations[@]}" \
          --tag "$IMG_REPO:latest" \
          "$IMG_REPO:$IMG_TAG-amd64" \
          "$IMG_REPO:$IMG_TAG-arm64"

  release:
    needs: [test, docker-image, docker-manifest]
    permissions:
      actions: read
      contents: write
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: haskell-actions/setup@v2
      with:
        enable-stack: true
    - run: |
        set -evx
        mkdir -p "$RUNNER_TEMP/dist/"
        stack sdist
        cp "$(stack path --dist-dir)"/submark-*.tar.gz "$RUNNER_TEMP/dist/"
    - run: |
        set -evx
        mkdir -p "$RUNNER_TEMP/linux-x86_64/"
        mkdir -p "$RUNNER_TEMP/linux-aarch64/"
        mkdir -p "$RUNNER_TEMP/macos-x86_64/"
        mkdir -p "$RUNNER_TEMP/macos-aarch64/"
        mkdir -p "$RUNNER_TEMP/windows/"
    - uses: actions/download-artifact@v8
      with:
        name: Linux-x86_64-musl-executable
        path: ${{ runner.temp }}/linux-x86_64
    - uses: actions/download-artifact@v8
      with:
        name: Linux-aarch64-musl-executable
        path: ${{ runner.temp }}/linux-aarch64
    - uses: actions/download-artifact@v8
      with:
        name: macOS-x86_64-executable
        path: ${{ runner.temp }}/macos-x86_64
    - uses: actions/download-artifact@v8
      with:
        name: macOS-aarch64-executable
        path: ${{ runner.temp }}/macos-aarch64
    - uses: actions/download-artifact@v8
      with:
        name: Windows-win64-executable
        path: ${{ runner.temp }}/windows
    - run: |
        set -evx
        mv "$RUNNER_TEMP/linux-x86_64/submark" \
          "$RUNNER_TEMP/dist/submark-linux-x86_64"
        mv "$RUNNER_TEMP/linux-aarch64/submark" \
          "$RUNNER_TEMP/dist/submark-linux-aarch64"
        mv "$RUNNER_TEMP/macos-x86_64/submark" \
          "$RUNNER_TEMP/dist/submark-darwin-x86_64"
        mv "$RUNNER_TEMP/macos-aarch64/submark" \
          "$RUNNER_TEMP/dist/submark-darwin-aarch64"
        mv "$RUNNER_TEMP/windows/submark.exe" \
          "$RUNNER_TEMP/dist/submark-win64.exe"
    - run: |
        set -evx
        chmod +x "$RUNNER_TEMP/dist/submark-linux-x86_64"
        "$RUNNER_TEMP/dist/submark-linux-x86_64" \
          --h2 "Version $(stack query locals submark version)" \
          --omit-heading \
          --out-file "$RUNNER_TEMP/dist/RELEASE.md" \
          CHANGELOG.md
    - uses: actions/upload-artifact@v7
      with:
        name: dist
        path: ${{ runner.temp }}/dist/
        if-no-files-found: error
    - if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body_path: ${{ runner.temp }}/dist/RELEASE.md
        name: submark ${{ github.ref_name }}
        files: |
          ${{ runner.temp }}/dist/submark-linux-x86_64
          ${{ runner.temp }}/dist/submark-linux-aarch64
          ${{ runner.temp }}/dist/submark-darwin-x86_64
          ${{ runner.temp }}/dist/submark-darwin-aarch64
          ${{ runner.temp }}/dist/submark-win64.exe
          ${{ runner.temp }}/dist/submark-${{ github.ref_name }}.tar.gz
    - if: github.ref_type == 'tag'
      run: stack upload --no-terminal --ignore-check .
      env:
        HACKAGE_USERNAME: ${{ secrets.HACKAGE_USERNAME }}
        HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
